### ISSUE TITLE
set_params()

### ISSUE THREAD

**Issue by Rock-n-Rolli** [jnelson18/pyquantrf#1]
When calling the function set_params() of the QuantileRandomForestRegressor class an error is raised due to a missing point between `forest` and `set_params`. However, I am not sure, if one really wants to return `this.forest.set_params(**params)` since it will return an instance of a usual RandomForest Regressor instead of a QuantileRandomForestRegressor instance. I'd suggest changing the code of this function to something like
``` 
this.forest = this.forest.set_params(**params)
return this
```

**Comment by jnelson18** [comment]
Good point, I updated this in the master branch and it no longer returns anything so as to not be confusing.
