### ISSUE TITLE
Install on python >= 3.8

### ISSUE THREAD

**Issue by nmdwolf** [jnelson18/pyquantrf#2]
When trying to install the package on Python 3.8 or higher, the following error pops up:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyquantrf -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.10
```

The weird thing is that all files indicate that the only dependency should be Python >= 3.7. Is it possible that the issue is similar to the one in [https://github.com/conda/conda-build/issues/4399](url) ?

**Comment by jnelson18** [comment]
Yes I also had this issue, I'm not completely sure how the flexible dependencies work. So in the newest version I just removed the pinned python version all together. My test with Python 3.10 worked just fine.
